config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :local_storages
  resources :users
  resources :medicines
  resources :dashboards
  resources :patients
  resources :stocks
  resources :checkouts
  resources :shipments

  get '/checkout/storage', to: 'checkouts#select_unit'
  get '/checkout/medicine', to: 'checkouts#select_medicine'
  get '/shipment/storage', to: 'shipments#select_unit'
  get '/shipment/medicine', to: 'shipments#select_medicine'
  post '/users/login', to: 'users#login'
  post '/sign_up', to: 'users#sign_up'
  get '/search_ubs', to: 'local_storages#ask_local'
  post '/query_results', to: 'local_storages#query_results'
  get '/search_medicine', to: 'medicines#ask_local'
  post 'medicines/query_results', to: 'medicines#query_results'

  root to: 'dashboards#sign_in'

end

app/models/local_storage.rb
class LocalStorage
  include Guacamole::Model

  attribute :name, String
  attribute :city, String
  attribute :vlr_latitude, String
  attribute :vlr_longitude, String
  attribute :cod_munic, String
  attribute :cod_cnes, String
  attribute :dsc_endereco, String
  attribute :dsc_bairro, String
  attribute :dsc_telefone, String
  attribute :dsc_estrut_fisic_ambiencia, String
  attribute :dsc_adap_defic_fisic_idosos, String
  attribute :dsc_equipamentos, String
  attribute :dsc_medicamentos, String
  attribute :medicines, Array[Medicine], coerce: false

end

app/controllers/local_storages_controller.rb
class LocalStoragesController < ApplicationController

    #mostrar lista de unit_cares
    #mostrar unit_care
    #mostrar remedio

    #novo local_storage
    #novo remedio
    #editar available de remedio + ou -
  
    def index
        @storages = LocalStoragesCollection.all
    end
  
    def show
      @storage = LocalStoragesCollection.by_key params[:id]
      @stocks = StocksCollection.by_example(local_storage: @storage.key.to_i)
      @medicines = {}
      unless @stocks.nil?
        @stocks.each do |s|
          medicine = MedicinesCollection.by_key s.medicine
          puts medicine
          @medicines[medicine.key] = medicine.nomeMedicamento
        end
      end
    end
  
    def new
      @local_storage = LocalStorage.new
    end


    #pinkie = Pony.new(name: "Pinkie Pie")
    #PoniesCollection.save pinkie
    def create
        local_storage = LocalStorage.new(local_storage_params)
        LocalStoragesCollection.save local_storage
    
        respond_to do |format|
          format.html { redirect_to local_storages_path, notice: 'Unidade foi criada.' }
        end
    end

    #existing_pony.name = "Applejack"
    #PoniesCollection.save existing_pony

    def update
      respond_to do |format|
        if @patient.update(patient_params)
          format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
          format.json { render :show, status: :ok, location: @patient }
        else
          format.html { render :edit }
          format.json { render json: @patient.errors, status: :unprocessable_entity }
        end
      end
    end
  
    #PoniesCollection.delete existing_pony
    def destroy
      @patient.destroy
      respond_to do |format|
        format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    def ask_local
    end

    def query_results
      city = params[:city]
      @local_storages = LocalStoragesCollection.by_example(city: city)
    end
  
    private
  
      def local_storage_params
        params.require(:local_storage).permit(:name, :city, medicines: [
            :cnpj,
            :razaoSocial,
            :noRegistro,
            :codApresentacao,
            :codBarras,
            :nomeMedicamento,
            :descricao,
            :registroCAS,
            :nomeSubstancia,
            :tipoProduto,
            :vendaHospital,
            :listaCap,
            :listaConfaz,
            :preco,
            :precoTax,
            :available
        ])
      end
  end
  

app/helpers/local_storages_helper.rb
module LocalStoragesHelper
end

app/views/local_storages/ask_local.html.erb
<%= dialog_sm do %>
  <div class="card shadow">
    <div class="card-body">
      <%= bootstrap_form_tag url: 'query_results' do |f| %>
        <%= f.text_field :city, autofocus: true%>
        <%= f.submit "Pesquisar", class: "btn btn-primary btn-block" %>
      <% end %>
      <hr/>
    </div>
  </div>
<% end %>

app/views/local_storages/index.html.erb
<%= dialog_body do %>
    <div class="row mt-5 mb-5 pull-right">
        <%= link_to "Nova Unidade", new_local_storage_path, class: "btn btn-primary"%>
    </div>

    <div class="row">
        <div class="mb-5">
            <h3> Lista de unidades de saúde </h3>
        </div>
    </div>
    <table class="table table-centered">
        <tr>
            <th> Nome </th>
            <th> Cidade </th>
            <th> </th>
        </tr>
        <% @storages.each do |ls| %>
            <tr>
                <td> <%= ls.name %> </td>
                <td> <%= ls.city %> </td>
                <td> <%= link_to "Detalhes", local_storage_path(ls.key)%>
            </tr>
        <% end %>
    </table>
<% end %>

app/views/local_storages/new.html.erb
<%= dialog_sm do %>
  <div class="card shadow">
    <div class="card-body">
      <h4 class="mb-3"> Nova unidade </h4>
        <%= bootstrap_form_for @local_storage, html: {class: "nifty_form"} do |f| %>
          <%= f.text_field :name %>
          <%= f.text_field :city %>
          <%= f.submit "Create" %>
        <% end %>
        <hr/>
    </div>
  </div>
<% end %>

app/views/local_storages/query_results.html.erb
<%= dialog_body do %>

    <div class="row">
        <div class="mb-5">
            <h3> Resultados </h3>
        </div>
    </div>
    <table class="table table-centered">
        <% @local_storages.each do |ls| %>
            <tr>
                <td> <%= ls.name %> </td>
                <td> <%= ls.city %> </td>
                <td> <%= link_to "Detalhes", local_storage_path(ls.key)%>
            </tr>
        <% end %>
    </table>
<% end %>

app/views/local_storages/show.html.erb
<%= dialog_body do %>
    <div class="row">
        <div class="mb-5">
            <h3> <%=@storage.name %> </h3>
        </div>
    </div>
    <table class="table table-centered">
        <tr>
            <td> <strong> Nome </strong> </td>
            <td> <%= @storage.name %> </td>
        </tr>
        <tr>
            <td> <strong>Cidade </strong> </td>
            <td> <%= @storage.city %> </td>
        </tr>
        <tr>
            <td> <strong>Codigo Municipal </strong> </td>
            <td> <%= @storage.cod_munic %> </td>
        </tr>
        <tr>
            <td> <strong>Cod cnes </strong> </td>
            <td> <%= @storage.cod_cnes %> </td>
        </tr>
        <tr>
            <td> <strong>Endereço </strong> </td>
            <td> <%= @storage.dsc_endereco %> </td>
        </tr>
        <tr>
            <td> <strong>Bairro </strong> </td>
            <td> <%= @storage.dsc_bairro %> </td>
        </tr>
        <tr>
            <td> <strong>Telefone </strong> </td>
            <td> <%= @storage.dsc_telefone %> </td>
        </tr>
        <tr>
            <td> <strong>dsc_estrut_fisic_ambiencia </strong> </td>
            <td> <%= @storage.dsc_estrut_fisic_ambiencia %> </td>
        </tr>
        <tr>
            <td> <strong>dsc_adap_defic_fisic_idosos </strong> </td>
            <td> <%= @storage.dsc_adap_defic_fisic_idosos %> </td>
        </tr>
        <tr>
            <td> <strong>dsc_equipamentos </strong> </td>
            <td> <%= @storage.dsc_equipamentos %> </td>
        </tr>
        <tr>
            <td> <strong>dsc_medicamentos</strong> </td>
            <td> <%= @storage.dsc_medicamentos %> </td>
        </tr>
        <tr>
            <td> <strong>latitude</strong> </td>
            <td> <%= @storage.vlr_latitude %> </td>
        </tr>
        <tr>
            <td> <strong>longitude</strong> </td>
            <td> <%= @storage.vlr_longitude %> </td>
        </tr>
    </table>

<% unless @stocks.nil?%>
    <table class="table table-centered">
        <tr> 
            <th> Nome medicamento </th>
            <th> Quantidade </th>
        </tr>
        <% @stocks.each do |s| %>
            <tr>
                <td> <%= @medicines[s.medicine.to_s] %> </td>
                <td> <%= s.quantidade%> </td>
            </tr>
        <% end %>
    </table>
    <% end %>
<% end %>