config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :local_storages
  resources :users
  resources :medicines
  resources :dashboards
  resources :patients
  resources :stocks
  resources :checkouts
  resources :shipments

  get '/checkout/storage', to: 'checkouts#select_unit'
  get '/checkout/medicine', to: 'checkouts#select_medicine'
  get '/shipment/storage', to: 'shipments#select_unit'
  get '/shipment/medicine', to: 'shipments#select_medicine'
  post '/users/login', to: 'users#login'
  post '/sign_up', to: 'users#sign_up'
  get '/search_ubs', to: 'local_storages#ask_local'
  post '/query_results', to: 'local_storages#query_results'
  get '/search_medicine', to: 'medicines#ask_local'
  post 'medicines/query_results', to: 'medicines#query_results'

  root to: 'dashboards#sign_in'

end

app/models/user.rb
class User
  include Guacamole::Model

  attribute :name, String
  attribute :email, String
  attribute :password, String
  attribute :role, String
  attribute :cpf, String
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


    #some_ponies = PoniesCollection.by_example(color: 'green').limit(10)
    # => #<Guacamole::Query:0x1212 …>
    #some_ponies.first
    # The request to the database is made
    # => #<Pony:0x90u81 …>

    #pony = PoniesCollection.by_key "303"

    def index
        @users = UsersCollection.all
    end

    def show
        @user = UsersCollection.by_key params[:id]
    end

    def login
        user = UsersCollection.by_example(email: params[:email])
        if user.first.password == params[:password]
            flash[:success] = "Bem vindo"
            redirect_to dashboards_path   
        else
            flash[:alert] = "Login e/ou senha incorreto"
            redirect_to "/"
        end
    end

    def new
        @user = User.new
    end

    def sign_up
        @user = User.new
        respond_to do |format|
            format.html { render :layout => 'static' }
        end
    end
  
    def create
        @user = User.new(user_params)
        user = @user
        UsersCollection.save user
        respond_to do |format|
            format.html { redirect_to users_path, notice: 'Bem vindo.' }
            format.json { head :no_content }
        end
    end

    def edit
    end

    def destroy
        @user = UsersCollection.by_key params[:id]
        UsersCollection.delete @user
        respond_to do |format|
            format.html { redirect_to users_path, notice: 'Destruido.' }
            format.json { head :no_content }
        end

    end

    private
  
        def user_params
            params.require(:user).permit(:email, :password, :name, :cpf, :role)
        end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<%= dialog_body do %>
<div class="row mt-5 mb-5 pull-right">
        <%= link_to "Novo Funcionário", new_user_path, class: "btn btn-primary"%>
    </div>
  <h3 class="mb-5"> Lista de funcionários </h3>
  <% unless @users.nil?%>
    <table class="table table-bordered">
      <tr>
          <th> Key </th>       
          <th> Nome </th>
          <th> CPF </th>
          <th> Cargo </th>
          <th> E-mail </th>
          <th> </th>
          <th> </th>
      </tr>
      <% @users.each do |u| %>
        <tr>
            <td><%= u.key %></td>
            <td><%= u.name %></td>
            <td><%= u.cpf %></td>
            <td><%= u.role %></td>
            <td><%= u.email %></td>
            <td> <%= link_to "Detalhes", user_path(u.key)%>
            <td> <%= link_to "Deletar", user_path(u.key), method: :delete%>
        </tr>
      <% end %>
    </table>
  <% end %>
<% end %>

app/views/users/new.html.erb
<%= render "form", user: @user %>

app/views/users/sign_up.html.erb
<%= render "form", user: @user %>