config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :local_storages
  resources :users
  resources :medicines
  resources :dashboards
  resources :patients
  resources :stocks
  resources :checkouts
  resources :shipments

  get '/checkout/storage', to: 'checkouts#select_unit'
  get '/checkout/medicine', to: 'checkouts#select_medicine'
  get '/shipment/storage', to: 'shipments#select_unit'
  get '/shipment/medicine', to: 'shipments#select_medicine'
  post '/users/login', to: 'users#login'
  post '/sign_up', to: 'users#sign_up'
  get '/search_ubs', to: 'local_storages#ask_local'
  post '/query_results', to: 'local_storages#query_results'
  get '/search_medicine', to: 'medicines#ask_local'
  post 'medicines/query_results', to: 'medicines#query_results'

  root to: 'dashboards#sign_in'

end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-light mb-3 shadow-sm navbar-expand-lg navbar-app">
  <% if is_modal %>
    <a class="navbar-brand" onclick="javascript:window.history.back()">
      <i class="fas fa-chevron-left"></i>
    </a>
  <% else %>
    <a class="navbar-brand" href="<%= dashboards_path %>">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="<%= dashboards_path %>">
              Home
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= local_storages_path %>">
              Unidades de Atendimento
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= users_path %>">
            Funcionários
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= medicines_path %>">
            Medicamentos
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= patients_path %>">
            Pacientes
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= stocks_path %>">
            Estoque
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= checkouts_path %>">
            Retiradas
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= shipments_path %>">
            Recebimentos
          </a>
        </li>
      </ul>
    </div>
  <% end %>
</nav>