config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :local_storages
  resources :users
  resources :medicines
  resources :dashboards
  resources :patients
  resources :stocks
  resources :checkouts
  resources :shipments

  get '/checkout/storage', to: 'checkouts#select_unit'
  get '/checkout/medicine', to: 'checkouts#select_medicine'
  get '/shipment/storage', to: 'shipments#select_unit'
  get '/shipment/medicine', to: 'shipments#select_medicine'
  post '/users/login', to: 'users#login'
  post '/sign_up', to: 'users#sign_up'
  get '/search_ubs', to: 'local_storages#ask_local'
  post '/query_results', to: 'local_storages#query_results'
  get '/search_medicine', to: 'medicines#ask_local'
  post 'medicines/query_results', to: 'medicines#query_results'

  root to: 'dashboards#sign_in'

end

app/models/patient.rb
class Patient
    include Guacamole::Model
  
    attribute :name, String
    attribute :cpf, String
    attribute :telefone, String

end
  

app/controllers/patients_controller.rb
class PatientsController < ApplicationController


    #some_ponies = PoniesCollection.by_example(color: 'green').limit(10)
    # => #<Guacamole::Query:0x1212 …>
    #some_ponies.first
    # The request to the database is made
    # => #<Pony:0x90u81 …>
    def index
        @patients = PatientsCollection.all
    end

    def show
    end

    def new
        @patient = Patient.new
    end
  
    def create
        @patient = Patient.new(patient_params)
        patient = @patient
        PatientsCollection.save patient
        respond_to do |format|
            format.html { redirect_to patients_path, notice: 'Bem vindo.' }
            format.json { head :no_content }
        end
    end

    def edit
    end

    private
  
        def patient_params
            params.require(:patient).permit(:telefone, :name, :cpf)
        end
end

app/views/patients/_form.html.erb
<%= dialog_sm do %>
  <div class="card shadow">
    <div class="card-body">
      <h4 class="mb-3"> Novo paciente </h4>
        <%= bootstrap_form_for patient, html: {class: "nifty_form"} do |f| %>
        <%= f.text_field :name %>
        <%= f.text_field :cpf %>
        <%= f.text_field :telefone %>

        <%= f.submit "Criar" %>
        <% end %>
      <hr/>
    </div>
  </div>
<% end %>

app/views/patients/index.html.erb
<%= dialog_body do %>
<div class="row mt-5 mb-5 pull-right">
        <%= link_to "Novo Paciente", new_patient_path, class: "btn btn-primary"%>
    </div>
  <h3 class="mb-5"> Lista de pacientes </h3>
  <% unless @patients.nil?%>
    <table class="table table-bordered">
      <tr>
          <th> Key </th>       
          <th> Nome </th>
          <th> CPF </th>
          <th> Telefone </th>
          <th> </th>
          <th> </th>
      </tr>
      <% @patients.each do |p| %>
        <tr>
            <td><%= p.key %></td>
            <td><%= p.name %></td>
            <td><%= p.cpf %></td>
            <td><%= p.telefone %></td>
            <td> <%= link_to "Detalhes", patient_path(p.key)%>
            <td> <%= link_to "Deletar", patient_path(p.key), method: :delete%>
        </tr>
      <% end %>
    </table>
  <% end %>
<% end %>

app/views/patients/new.html.erb
<%= render "form", patient: @patient %>